// Teste da API REST de Prestadores
@baseURL = http://localhost:4000/api/prestadores

// GET - Lista todos os prestadores
GET {{baseURL}}/?limit=3&skip=0
Content-Type: application/json
acess-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjYzOTYyMGNiNGJjM2U1MDhkNTJjM2EyIn0sImlhdCI6MTcxNTAzNzQwMywiZXhwIjoxNzE1MTIzODAzfQ.DccmH-avax74bqCRKluZrwXjhqjDUMFl2DES65gvK6w

###
// GET - Lista o prestador pelo ID
GET {{baseURL}}/id/663972280c00461cc97ef4ad
Content-Type: application/json
acess-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjYzOTYyMGNiNGJjM2U1MDhkNTJjM2EyIn0sImlhdCI6MTcxNTAzNzQwMywiZXhwIjoxNzE1MTIzODAzfQ.DccmH-avax74bqCRKluZrwXjhqjDUMFl2DES65gvK6w

###
// GET - Lista o prestador pela razão social ou fantasia
GET {{baseURL}}/razao/maria
Content-Type: application/json
acess-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjYzOTYyMGNiNGJjM2U1MDhkNTJjM2EyIn0sImlhdCI6MTcxNTAzNzQwMywiZXhwIjoxNzE1MTIzODAzfQ.DccmH-avax74bqCRKluZrwXjhqjDUMFl2DES65gvK6w

###
// DELETE - Remove o prestador pelo id
DELETE {{baseURL}}/id/65ef96029c4ad0c824292780
Content-Type: application/json
acess-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjYzOTYyMGNiNGJjM2U1MDhkNTJjM2EyIn0sImlhdCI6MTcxNTAzNzQwMywiZXhwIjoxNzE1MTIzODAzfQ.DccmH-avax74bqCRKluZrwXjhqjDUMFl2DES65gvK6w

###
//POST - Insere um novo prestador pelo objeto
POST {{baseURL}}
Content-Type: application/json
acess-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjYzOTYyMGNiNGJjM2U1MDhkNTJjM2EyIn0sImlhdCI6MTcxNTAzNzQwMywiZXhwIjoxNzE1MTIzODAzfQ.DccmH-avax74bqCRKluZrwXjhqjDUMFl2DES65gvK6w

{
    "cnpj": "01234567891111",
    "razao_social": "JOSÉ LOPES TRANSPORTES LTDA.",
    "cep": "18110680",
    "endereco":{
        "logradouro": "Av. Pesidente Kennedy, 120",
        "complemento": "",
        "bairro": "Centro",
        "localidade": "Votorantim",
        "uf": "SP"
    },
    "cnae_fiscal": 451510,
    "nome_fantasia": "JOSELO",
    "data_inicio_atividade": "2022-07-22",
    "localização": {
        "type": "Point",
        "coordinates": [-23.2904, -47.2963]
    }
}


###
//PUT - Altera um prestador pelo _id já existente
PUT {{baseURL}}
Content-Type: application/json
acess-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjYzOTYyMGNiNGJjM2U1MDhkNTJjM2EyIn0sImlhdCI6MTcxNTAzNzQwMywiZXhwIjoxNzE1MTIzODAzfQ.DccmH-avax74bqCRKluZrwXjhqjDUMFl2DES65gvK6w

{
    "_id": "65ef96029c4ad0c824292780",
    "cnpj": "01234567891029",
    "razao_social": "SERVIÇOS MOTOBOY ALTERADO LTDA.",
    "cep": "11112302",
    "endereco": {
      "logradouro": "Av. Pesidente Kennedy, 333",
      "complemento": "",
      "bairro": "Centro",
      "localidade": "Votorantim",
      "uf": "SP"
    },
    "cnae_fiscal": 451510,
    "nome_fantasia": "ZÉ MOTOBOY",
    "data_inicio_atividade": "2022-07-22",
    "localização": {
      "type": "Point",
      "coordinates": [
        -23.2904,
        -47.2963
      ]
    }
  }
